export const marketLinkages = [
  {
    id: 'ml1',
    title: 'Nairobi Export Market Connection',
    description: 'Connect with international buyers looking for fresh Kenyan produce for export.',
    date: '2023-10-05',
    location: 'Nairobi County',
    organizer: 'Export Promotion Council',
    participants: 120,
    tags: ['export', 'international', 'certification'],
    providerName: 'Kenya Export Market Authority',
    // Fix: convert strings to arrays
    crops: ['Avocados', 'French Beans', 'Herbs'], // Was a string
    markets: ['EU', 'Middle East', 'Asia'], // Was a string
    type: 'Export Market',
    requirements: ['GLOBALG.A.P Certification', 'Minimum volume capacity', 'Consistent supply'],
    benefits: ['Premium prices', 'Long-term contracts', 'Technical support'],
    contactInfo: 'exports@kepc.org | +254 20 222 9219'
  },
  {
    id: 'ml2',
    title: 'Kisumu Fish Market Expansion',
    description: 'Opportunities for local fishermen to expand their market reach in Kisumu.',
    date: '2023-10-12',
    location: 'Kisumu County',
    organizer: 'Lake Victoria Fisheries Organization',
    participants: 85,
    tags: ['fish', 'local-market', 'sustainable-fishing'],
    providerName: 'Lake Basin Development Authority',
    crops: ['Tilapia', 'Nile Perch', 'Catfish'],
    markets: ['Local Restaurants', 'Regional Distributors', 'Export Processors'],
    type: 'Local Market',
    requirements: ['Adherence to fishing quotas', 'Quality control checks', 'Sustainable practices'],
    benefits: ['Access to credit facilities', 'Training programs', 'Market information'],
    contactInfo: 'fisheries@lbda.go.ke | +254 57 202 1045'
  },
  {
    id: 'ml3',
    title: 'Nakuru Dairy Cooperative Linkage',
    description: 'Linking dairy farmers in Nakuru with processors and retailers for better market access.',
    date: '2023-10-19',
    location: 'Nakuru County',
    organizer: 'Dairy Farmers Association of Kenya',
    participants: 150,
    tags: ['dairy', 'cooperative', 'processing', 'retail'],
    providerName: 'Kenya Dairy Board',
    crops: ['Milk', 'Cheese', 'Yogurt'],
    markets: ['Supermarkets', 'Hotels', 'Export Markets'],
    type: 'Dairy Market',
    requirements: ['KDB certification', 'Consistent supply', 'Quality standards'],
    benefits: ['Stable prices', 'Market security', 'Technical assistance'],
    contactInfo: 'dairy@kdb.go.ke | +254 20 359 8765'
  },
  {
    id: 'ml4',
    title: 'Eldoret Maize Farmers Connection',
    description: 'Connecting maize farmers in Eldoret with grain millers and buyers for improved market opportunities.',
    date: '2023-10-26',
    location: 'Uasin Gishu County',
    organizer: 'Cereal Growers Association',
    participants: 200,
    tags: ['maize', 'cereal', 'grain-milling', 'market-access'],
    providerName: 'National Cereals and Produce Board',
    crops: ['Maize', 'Wheat', 'Barley'],
    markets: ['Local Millers', 'Export Markets', 'Animal Feed Manufacturers'],
    type: 'Grain Market',
    requirements: ['Certified seeds', 'Proper storage', 'Quality control'],
    benefits: ['Guaranteed prices', 'Storage facilities', 'Market information'],
    contactInfo: 'cereals@ncpb.go.ke | +254 53 432 1098'
  },
  {
    id: 'ml5',
    title: 'Meru Coffee Auction and Trade Fair',
    description: 'An event for coffee farmers in Meru to auction their produce and connect with international traders.',
    date: '2023-11-02',
    location: 'Meru County',
    organizer: 'Coffee Directorate of Kenya',
    participants: 180,
    tags: ['coffee', 'auction', 'trade-fair', 'export'],
    providerName: 'Coffee Research Institute',
    crops: ['Arabica Coffee', 'Robusta Coffee'],
    markets: ['International Traders', 'Local Roasters', 'Coffee Shops'],
    type: 'Coffee Market',
    requirements: ['Coffee Board certification', 'Quality grading', 'Traceability'],
    benefits: ['Competitive prices', 'Direct sales', 'Market exposure'],
    contactInfo: 'coffee@cdk.go.ke | +254 64 301 2345'
  },
  {
    id: 'ml6',
    title: 'Mombasa Horticultural Produce Linkage',
    description: 'Linking horticultural farmers in Mombasa with exporters and hotels for better market access.',
    date: '2023-11-09',
    location: 'Mombasa County',
    organizer: 'Horticultural Crops Directorate',
    participants: 130,
    tags: ['horticultural', 'export', 'hotel-supply', 'market-access'],
    providerName: 'Kenya Flower Council',
    crops: ['Mangoes', 'Avocados', 'Pineapples'],
    markets: ['Export Markets', 'Local Hotels', 'Supermarkets'],
    type: 'Horticultural Market',
    requirements: ['KEPHIS certification', 'Quality standards', 'Consistent supply'],
    benefits: ['Stable prices', 'Market security', 'Technical assistance'],
    contactInfo: 'horticulture@kfc.org | +254 41 231 5678'
  },
  {
    id: 'ml7',
    title: 'Nyeri Tea Smallholders Connection',
    description: 'Connecting tea smallholders in Nyeri with processors and blenders for improved market opportunities.',
    date: '2023-11-16',
    location: 'Nyeri County',
    organizer: 'Tea Board of Kenya',
    participants: 160,
    tags: ['tea', 'smallholders', 'processing', 'blending'],
    providerName: 'Tea Research Foundation of Kenya',
    crops: ['Black Tea', 'Green Tea', 'Purple Tea'],
    markets: ['Export Markets', 'Local Blenders', 'Tea Packers'],
    type: 'Tea Market',
    requirements: ['TBK certification', 'Quality standards', 'Consistent supply'],
    benefits: ['Stable prices', 'Market security', 'Technical assistance'],
    contactInfo: 'tea@tbk.go.ke | +254 61 203 4567'
  },
  {
    id: 'ml8',
    title: 'Kisii Banana Farmers Linkage',
    description: 'Linking banana farmers in Kisii with processors and retailers for better market access.',
    date: '2023-11-23',
    location: 'Kisii County',
    organizer: 'Kenya National Farmers Federation',
    participants: 140,
    tags: ['banana', 'processing', 'retail', 'market-access'],
    providerName: 'Agricultural and Food Authority',
    crops: ['Cavendish Banana', 'Plantain', 'Apple Banana'],
    markets: ['Local Retailers', 'Export Markets', 'Snack Manufacturers'],
    type: 'Banana Market',
    requirements: ['KEPHIS certification', 'Quality standards', 'Consistent supply'],
    benefits: ['Stable prices', 'Market security', 'Technical assistance'],
    contactInfo: 'banana@afa.go.ke | +254 58 201 2345'
  }
];

export default marketLinkages;
