// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwcduhvwkihpnuaoflps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3Y2R1aHZ3a2locG51YW9mbHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDc2MDksImV4cCI6MjA1NzY4MzYwOX0.JXPGnrntA_M-OhhhY6U0Nc70-2jEyVKXENoI-gWnGFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);